"use client"

import { useEffect, useState } from "react"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { DownloadIcon, FileTextIcon, FileX2Icon } from "lucide-react"
import { toast } from "sonner"

interface MonthlyReport {
  id: number
  month: number
  year: number
  total_income: string
  total_expenses: string
  top_expense_category: string
}

export default function ReportsPage() {
  const [reports, setReports] = useState<MonthlyReport[]>([])
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    const fetchReports = async () => {
      const token = localStorage.getItem("access")
      if (!token) return

      try {
        const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/reports/`, {
          headers: { Authorization: `Bearer ${token}` },
        })

        if (res.ok) {
          const data = await res.json()
          setReports(data)
        }
      } catch (error) {
        toast.error("Failed to load reports")
      } finally {
        setIsLoading(false)
      }
    }

    fetchReports()
  }, [])

  const handleDownload = (monthName: string, year: number) => {
    // For the hackathon demo, we will simulate a PDF generation
    // In a real app, you would fetch a generated PDF blob from Django here
    toast.info(`Generating PDF for ${monthName} ${year}...`)

    setTimeout(() => {
      toast.success(`${monthName}_${year}_Financial_Report.pdf downloaded!`)
    }, 2000)
  }

  const handleGenerateNow = async () => {
    setIsLoading(true)
    const token = localStorage.getItem("access")

    try {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/reports/generate/`,
        {
          method: "POST",
          headers: { Authorization: `Bearer ${token}` },
        }
      )

      if (res.ok) {
        toast.success("Current month's report generated!")
        // Refresh the page to show the new report
        window.location.reload()
      } else {
        toast.error("Failed to generate report.")
      }
    } catch (error) {
      toast.error("Network error")
    } finally {
      setIsLoading(false)
    }
  }

  const formatMoney = (amount: string | number) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      maximumFractionDigits: 0,
    }).format(typeof amount === 'string' ? parseFloat(amount) : amount)
  }

  // Convert month numbers (1-12) to month names (January-December)
  const getMonthName = (monthNumber: number) => {
    const date = new Date()
    date.setMonth(monthNumber - 1)
    return date.toLocaleString('en-US', { month: 'long' })
  }

  return (
    <div className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-semibold md:text-2xl">Monthly Reports</h1>

        {/* The Hackathon Rescue Button */}
        <Button onClick={handleGenerateNow} size="sm">
          Generate Current Month
        </Button>
      </div>

      {isLoading ? (
        <div className="mt-10 animate-pulse text-muted-foreground">
          Loading your reports...
        </div>
      ) : reports.length === 0 ? (
        <div className="mt-6 flex max-w-3xl flex-col items-center justify-center rounded-lg border-2 border-dashed p-12 text-muted-foreground">
          <FileX2Icon className="mb-4 h-10 w-10 opacity-50" />
          <p className="text-lg font-medium text-foreground">
            No reports generated yet.
          </p>
          <p className="mt-2 text-center text-sm">
            Reports are automatically generated by the system at the end of each
            month based on your transaction history. Check back later!
          </p>
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {reports.map((report) => {
            const monthName = getMonthName(report.month)

            return (
              <Card
                key={report.id}
                className="flex flex-col transition-colors hover:border-primary/50"
              >
                <CardHeader className="flex flex-row items-center gap-4 pb-4">
                  <div className="rounded-lg bg-primary/10 p-3">
                    <FileTextIcon className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <CardTitle className="text-lg">
                      {monthName} {report.year}
                    </CardTitle>
                    <CardDescription>
                      Official Financial Summary
                    </CardDescription>
                  </div>
                </CardHeader>

                <CardContent className="flex flex-1 flex-col">
                  {/* Data Preview Area */}
                  <div className="mb-6 grid flex-1 grid-cols-2 gap-4 rounded-md bg-muted/30 p-4">
                    <div>
                      <p className="text-xs text-muted-foreground">
                        Total Income
                      </p>
                      <p className="font-semibold text-green-500">
                        {formatMoney(report.total_income)}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">
                        Total Expenses
                      </p>
                      <p className="font-semibold text-red-500">
                        {formatMoney(report.total_expenses)}
                      </p>
                    </div>
                    <div className="col-span-2 border-t border-border/50 pt-2">
                      <p className="text-xs text-muted-foreground">
                        Top Expense Category
                      </p>
                      <p className="font-medium">
                        {report.top_expense_category || "N/A"}
                      </p>
                    </div>
                  </div>

                  <Button
                    variant="outline"
                    className="mt-auto w-full"
                    onClick={() => handleDownload(monthName, report.year)}
                  >
                    <DownloadIcon className="mr-2 h-4 w-4" />
                    Download PDF
                  </Button>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}